version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:08e7779e47cac1874e09dcf6f35dad4946c1a46b

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test
      - elixir/test
      - elixir/lint
